# sudo apt update && sudo apt upgrade
find . -name '*.mp3' -type f -print
find . -name '*.mov' -type f -print
find . -name '*.mp4' -type f -print
find . -name '*.avi' -type f -print
find . -name '*.mpg' -type f -print
find . -name '*.mpeg' -type f -print
find . -name '*.flac' -type f -print
find . -name '*.m4a' -type f -print
find . -name '*.flv' -type f -print
find . -name '*.ogg' -type f -print
find . -name '*.mov' -type f -print
sudo apt update && sudo apt upgrade
find /home -name '*.gif' -type f -print
find /home -name '*.png' -type f -print
find /home -name '*.jpg' -type f -print
find /home -name '*.jpeg' -type f -print
find /home -name '*.tar.gz' -type f -print
find /home -name '*.appImage' -type f -print
find /home -name '*.exe' -type f -print
find /home -name '*.html' -type f -print
sudo apt update && sudo apt upgrade
find /home -name '*.js' -type f -print
find /home -name '*.jpeg' -type f -print
find /home -name '*.cpp' -type f -print
find /home -name '*.py' -type f -print
find /home -name '*.java' -type f -print
find /home -name '*.class' -type f -print
