chmod +x analyzenetworktraffic.sh
chmod +x checkfileintergrity.sh
chmod +x findrecentlogins.sh
chmod +x incidentresponse.sh
chmod +x inodeanalysis.sh
chmod +x malwareanalysis.sh
chmod +x networkforensics.sh
chmod +x Checkinit.sh
chmod +x Installsudoandapt.sh
chmod +x antivirus_optimization_ufw_passwords_ipv6.sh
chmod +x checkAllPorts.sh
chmod +x filefinding.sh
chmod +x gemini.sh
