chmod +x ChatGPT.sh
chmod +x gemini.sh
chmod +x GeneralAntivirus.sh
chmod +x SecuityBasicCheck.sh
chmod +x Lynis.sh
chmod +x auditlogcheck.sh
chmod +x analyzenetworktraffic.sh
chmod +x checkfileintegrity.sh
chmod +x findrecentlogins.sh
chmod +x incidentresponse.sh
chmod +x inodeanalysis.sh
chmod +x malwareanalysis.sh
chmod +x networkforensics.sh
chmod +x Checkinit.sh
chmod +x show_hidden_files.sh
chmod +x checkAllPorts.sh
chmod +x ports_and_ufw.sh
chmod +x Installsudoandapt.sh
chmod +x checkapplications.sh
chmod +x filefinding.sh
chmod +x scoringchecks.sh
chmod +x systemhardening1.sh
